package dev.ryu4696.hitandblow;

import android.animation.ValueAnimator;
import android.app.Activity;
import android.graphics.*;
import android.media.*;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.*;
import android.view.animation.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;

public class MainActivity extends Activity {
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setNavigationBarColor(Color.BLACK);setContentView(new Game());}
 class Game extends View {
  final int[] C={0xff2459df,0xffed3838,0xff25bd43,0xffffd21d,0xffe85ccf,0xffe9eeeb};
  final int[] HX={150,277,403,528,652,777,901,1026};
  final int[][] GX={{150,150,150,150},{277,277,277,277},{403,403,403,403},{528,527,528,527},{652,652,652,652},{777,777,777,777},{901,901,901,901},{1026,1026,1026,1026}};
  final int[][] GY={{294,364,433,504},{294,364,434,504},{294,364,434,504},{294,364,433,504},{294,364,434,504},{294,364,434,504},{294,364,433,504},{294,364,434,504}};
  final int[][] MX={{134,167,134,167},{261,294,261,294},{387,420,387,420},{511,544,511,544},{636,669,636,669},{761,794,761,794},{885,918,885,918},{1009,1043,1009,1042}};
  final int[][] MY={{188,189,220,219},{189,189,219,220},{188,188,219,219},{189,189,220,220},{189,189,220,220},{189,189,219,219},{189,189,220,219},{189,188,220,220}};
  final int[] PX={399,494,590,686,781,877};
  final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);final Path path=new Path();final Bitmap bg;
  final ArrayList<int[]> tries=new ArrayList<>(),marks=new ArrayList<>(),editHistory=new ArrayList<>();final int[] now={-1,-1,-1,-1};final int[] answer=new int[4];
  final ArrayList<RectF> palette=new ArrayList<>();final RectF ok=new RectF(),undo=new RectF(),gear=new RectF(),restart=new RectF(),option=new RectF(),close=new RectF();
 final ToneGenerator tone=new ToneGenerator(AudioManager.STREAM_MUSIC,34);
  final Handler ui=new Handler(Looper.getMainLooper());final ExecutorService net=Executors.newSingleThreadExecutor();
  static final String API_KEY="AIzaSyB92Y8OCz28ADWazUmyRyFVGYEivqMtI7U";
  static final String DB="https://hitandblow-online-default-rtdb.asia-southeast1.firebasedatabase.app";
  static final int MENU=0,LOBBY=1,SECRET=2,PLAY=3;int screen=MENU;
  final RectF soloBtn=new RectF(),onlineBtn=new RectF(),createBtn=new RectF(),joinBtn=new RectF(),backBtn=new RectF(),secretOk=new RectF();
  final ArrayList<RectF> keys=new ArrayList<>();String roomCode="",uid="",token="",onlineMsg="";boolean online=false,host=false,ready=false,myTurn=false,busy=false,polling=false;String role="",opponentSecret="";int remoteMoveCount=0;
  boolean duplicates=false,ended=false,win=false,settings=false,dragging=false,dragMoved=false;int movingColor=-1,movingSlot=-1,selectedColor=-1,dragColor=-1,markCol=-1,lastHit=0,lastBlow=0;float putT=1,pinT=1,lidT=0,partyT=0,resultT=1,dragX,dragY,downX,downY;
  Game(){super(MainActivity.this);setLayerType(LAYER_TYPE_SOFTWARE,null);bg=BitmapFactory.decodeResource(getResources(),R.drawable.game_board_v6);newGame();screen=MENU;}
  void newGame(){tries.clear();marks.clear();editHistory.clear();Arrays.fill(now,-1);ended=win=dragging=false;selectedColor=dragColor=-1;putT=pinT=1;lidT=partyT=0;ArrayList<Integer>b=new ArrayList<>();for(int i=0;i<6;i++)b.add(i);Collections.shuffle(b);Random r=new Random();for(int i=0;i<4;i++)answer[i]=duplicates?r.nextInt(6):b.get(i);invalidate();}
  int filled(){int n=0;for(int v:now)if(v>=0)n++;return n;}
  int mix(int a,int b,float t){return Color.rgb((int)(Color.red(a)*(1-t)+Color.red(b)*t),(int)(Color.green(a)*(1-t)+Color.green(b)*t),(int)(Color.blue(a)*(1-t)+Color.blue(b)*t));}
  void rr(Canvas c,RectF r,float rad,int color){p.setShader(null);p.setStyle(Paint.Style.FILL);p.setColor(color);p.clearShadowLayer();c.drawRoundRect(r,rad,rad,p);}
  void text(Canvas c,String s,float x,float y,float z,int color){p.setShader(null);p.setStyle(Paint.Style.FILL);p.setTypeface(Typeface.create("sans",Typeface.BOLD));p.setTextAlign(Paint.Align.CENTER);p.setTextSize(z);p.setColor(color);c.drawText(s,x,y,p);}
  void marble(Canvas c,float x,float y,float r,int idx){int base=C[idx];p.setShader(new RadialGradient(x-r*.35f,y-r*.42f,r*1.35f,new int[]{mix(base,Color.WHITE,.54f),base,mix(base,Color.BLACK,.50f)},new float[]{0,.45f,1},Shader.TileMode.CLAMP));p.setStyle(Paint.Style.FILL);p.setShadowLayer(r*.28f,0,r*.23f,0xbb000000);c.drawCircle(x,y,r,p);p.clearShadowLayer();p.setShader(null);c.save();path.reset();path.addCircle(x,y,r*.87f,Path.Direction.CW);c.clipPath(path);p.setColor(0xb8ffffff);p.setStrokeCap(Paint.Cap.ROUND);p.setStrokeWidth(r*.22f);p.setStyle(Paint.Style.STROKE);
   if(idx==0){c.drawLine(x-r,y,x+r,y,p);c.drawLine(x,y-r,x,y+r,p);}else if(idx==1){p.setStyle(Paint.Style.FILL);float q=r*.61f;for(int a=-2;a<2;a++)for(int b=-2;b<2;b++)if((a+b)%2==0)c.drawRect(x+a*q,y+b*q,x+(a+1)*q,y+(b+1)*q,p);}else if(idx==2){for(int k=-1;k<=1;k++){path.reset();path.moveTo(x-r*1.2f,y+k*r*.72f);path.cubicTo(x-r*.5f,y+(k-.8f)*r*.72f,x+r*.2f,y+(k+.8f)*r*.72f,x+r*1.2f,y+k*r*.72f);c.drawPath(path,p);}}else if(idx==3){p.setStyle(Paint.Style.FILL);for(int a=-2;a<2;a++)for(int b=-2;b<2;b++){path.reset();path.moveTo(x+a*r*.75f,y+b*r*.75f-r*.28f);path.lineTo(x+a*r*.75f+r*.28f,y+b*r*.75f);path.lineTo(x+a*r*.75f,y+b*r*.75f+r*.28f);path.lineTo(x+a*r*.75f-r*.28f,y+b*r*.75f);path.close();c.drawPath(path,p);}}else if(idx==4){for(int k=-2;k<=2;k++)c.drawLine(x-r*1.5f+k*r*.62f,y+r,x+r*.5f+k*r*.62f,y-r,p);}else for(int k=-2;k<=2;k++)c.drawLine(x-r,y+k*r*.5f,x+r,y+k*r*.5f,p);c.restore();p.setStyle(Paint.Style.FILL);p.setColor(0xccffffff);c.drawOval(new RectF(x-r*.48f,y-r*.56f,x-r*.12f,y-r*.23f),p);}
  void peg(Canvas c,float x,float y,float r,boolean hit){int b=hit?0xffd86620:0xffeee9dd;p.setShader(new RadialGradient(x-r*.35f,y-r*.4f,r*1.3f,new int[]{Color.WHITE,b,mix(b,Color.BLACK,.45f)},new float[]{0,.42f,1},Shader.TileMode.CLAMP));p.setStyle(Paint.Style.FILL);p.setShadowLayer(r*.3f,0,r*.2f,0xcc000000);c.drawCircle(x,y,r,p);p.clearShadowLayer();p.setShader(null);}
  void answerLid(Canvas c,RectF r,float h){p.setAlpha(255);p.setShader(new LinearGradient(r.left,r.top,r.right,r.bottom,new int[]{0xff4b4a45,0xff17191a,0xff30302d},null,Shader.TileMode.CLAMP));p.setStyle(Paint.Style.FILL);p.setShadowLayer(h*.014f,0,h*.008f,0xdd000000);c.drawRoundRect(r,h*.015f,h*.015f,p);p.clearShadowLayer();p.setShader(null);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(h*.005f);p.setColor(0xffb59a67);c.drawRoundRect(r,h*.015f,h*.015f,p);p.setStrokeWidth(h*.002f);p.setColor(0xff5f5037);c.drawRoundRect(new RectF(r.left+h*.008f,r.top+h*.008f,r.right-h*.008f,r.bottom-h*.008f),h*.010f,h*.010f,p);if(r.height()>h*.10f){for(float y=r.top+h*.055f;y<r.bottom-h*.025f;y+=h*.050f){p.setColor(0x664f4536);c.drawLine(r.left+h*.010f,y,r.right-h*.010f,y,p);}float cx=r.centerX(),cy=r.centerY(),d=h*.034f;path.reset();path.moveTo(cx,cy-d);path.lineTo(cx+d,cy);path.lineTo(cx,cy+d);path.lineTo(cx-d,cy);path.close();p.setColor(0xffaa8b55);p.setStrokeWidth(h*.004f);c.drawPath(path,p);p.setColor(0xff252626);p.setStyle(Paint.Style.FILL);c.drawCircle(cx,cy,h*.008f,p);for(float yy:new float[]{r.top+h*.025f,r.bottom-h*.025f}){p.setAlpha(255);p.setShader(new RadialGradient(cx,yy,h*.010f,new int[]{0xffffe2a0,0xff806237,0xff171717},null,Shader.TileMode.CLAMP));c.drawCircle(cx,yy,h*.010f,p);p.setShader(null);}}p.setAlpha(255);}
  void panel(Canvas c,RectF r,float h){p.setShader(new LinearGradient(r.left,r.top,r.right,r.bottom,new int[]{0xee151616,0xf12c2b27,0xee111212},null,Shader.TileMode.CLAMP));p.setStyle(Paint.Style.FILL);p.setShadowLayer(h*.025f,0,h*.012f,0xdd000000);c.drawRoundRect(r,h*.026f,h*.026f,p);p.clearShadowLayer();p.setShader(null);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(h*.004f);p.setColor(0xffb89556);c.drawRoundRect(r,h*.026f,h*.026f,p);p.setStrokeWidth(h*.0015f);p.setColor(0xff5c4b30);c.drawRoundRect(new RectF(r.left+h*.012f,r.top+h*.012f,r.right-h*.012f,r.bottom-h*.012f),h*.018f,h*.018f,p);}
  void metalButton(Canvas c,RectF r,String label,boolean enabled,float h){int a=enabled?0xffa97930:0xff45423c;p.setShader(new LinearGradient(r.left,r.top,r.left,r.bottom,new int[]{mix(a,Color.WHITE,.16f),a,mix(a,Color.BLACK,.24f)},null,Shader.TileMode.CLAMP));p.setStyle(Paint.Style.FILL);c.drawRoundRect(r,h*.018f,h*.018f,p);p.setShader(null);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(h*.0025f);p.setColor(enabled?0xffe1c17e:0xff756d60);c.drawRoundRect(r,h*.018f,h*.018f,p);text(c,label,r.centerX(),r.centerY()+h*.012f,h*.033f,enabled?0xfffff3d7:0xffaaa397);}
  void drawMenu(Canvas c,float w,float h){c.drawBitmap(bg,null,new RectF(0,0,w,h),p);p.setColor(0x55000000);p.setStyle(Paint.Style.FILL);c.drawRect(0,0,w,h,p);RectF box=new RectF(.285f*w,.19f*h,.715f*w,.82f*h);panel(c,box,h);text(c,"HIT & BLOW",.5f*w,.31f*h,h*.061f,0xffffe9bd);text(c,"GAME TABLE",.5f*w,.365f*h,h*.021f,0xffbda778);soloBtn.set(.35f*w,.45f*h,.65f*w,.56f*h);onlineBtn.set(.35f*w,.62f*h,.65f*w,.73f*h);metalButton(c,soloBtn,"ひとりで遊ぶ",true,h);metalButton(c,onlineBtn,"オンライン対戦",true,h);}
  void drawLobby(Canvas c,float w,float h){c.drawBitmap(bg,null,new RectF(0,0,w,h),p);p.setColor(0x66000000);p.setStyle(Paint.Style.FILL);c.drawRect(0,0,w,h,p);RectF box=new RectF(.20f*w,.10f*h,.80f*w,.91f*h);panel(c,box,h);text(c,"ONLINE MATCH",.5f*w,.205f*h,h*.050f,0xffffe7b2);text(c,roomCode.length()==0?"—  —  —  —":spacedCode(),.5f*w,.325f*h,h*.072f,0xfffff0cc);text(c,onlineMsg,.5f*w,.385f*h,h*.024f,0xffcfbd99);keys.clear();for(int i=0;i<10;i++){int row=i<9?i/3:3,col=i<9?i%3:1;float cx=(.40f+col*.10f)*w,cy=(.47f+row*.092f)*h;RectF r=new RectF(cx-.038f*w,cy-.034f*h,cx+.038f*w,cy+.034f*h);keys.add(r);rr(c,r,h*.012f,0xff242522);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(2);p.setColor(0xff796440);c.drawRoundRect(r,h*.012f,h*.012f,p);text(c,String.valueOf(i<9?i+1:0),cx,cy+h*.013f,h*.038f,0xffffe8bd);}createBtn.set(.235f*w,.76f*h,.37f*w,.855f*h);joinBtn.set(.63f*w,.76f*h,.765f*w,.855f*h);backBtn.set(.055f*w,.055f*h,.14f*w,.13f*h);metalButton(c,createBtn,"部屋を作る",!busy,h);metalButton(c,joinBtn,"参加する",roomCode.length()==4&&!busy,h);metalButton(c,backBtn,"戻る",!busy,h);}
  String spacedCode(){StringBuilder s=new StringBuilder();for(int i=0;i<roomCode.length();i++){if(i>0)s.append("  ");s.append(roomCode.charAt(i));}for(int i=roomCode.length();i<4;i++)s.append("  —");return s.toString();}
  void drawSecret(Canvas c,float w,float h){c.drawBitmap(bg,null,new RectF(0,0,w,h),p);p.setColor(0x66000000);p.setStyle(Paint.Style.FILL);c.drawRect(0,0,w,h,p);RectF box=new RectF(.18f*w,.14f*h,.82f*w,.84f*h);panel(c,box,h);text(c,"SECRET CODE",.5f*w,.245f*h,h*.045f,0xffffe7b2);text(c,ready?"相手の準備を待っています":"相手に隠す4色を決める",.5f*w,.305f*h,h*.027f,0xffd8c7a8);float mr=h*.043f;for(int i=0;i<4;i++){float x=(.365f+i*.09f)*w,y=.425f*h;p.setStyle(Paint.Style.FILL);p.setColor(0xff111210);p.setShadowLayer(h*.014f,0,h*.008f,0xdd000000);c.drawCircle(x,y,mr*1.13f,p);p.clearShadowLayer();p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(h*.003f);p.setColor(now[i]<0?0xffc29b58:0xff66563d);c.drawCircle(x,y,mr*1.18f,p);if(now[i]>=0)marble(c,x,y,mr,now[i]);}
   palette.clear();for(int i=0;i<6;i++){float x=(.31f+i*.076f)*w,y=.585f*h;RectF r=new RectF(x-mr*1.3f,y-mr*1.3f,x+mr*1.3f,y+mr*1.3f);palette.add(r);marble(c,x,y,mr,i);if(i==selectedColor){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(h*.005f);p.setColor(0xffffcf62);p.setShadowLayer(h*.014f,0,0,0xffffb52f);c.drawCircle(x,y,mr*1.32f,p);p.clearShadowLayer();}}
   secretOk.set(.40f*w,.69f*h,.60f*w,.79f*h);metalButton(c,secretOk,"これで決定",filled()==4&&!ready,h);backBtn.set(.055f*w,.055f*h,.14f*w,.13f*h);metalButton(c,backBtn,"退出",!busy,h);if(roomCode.length()>0)text(c,"ROOM  "+roomCode,.5f*w,.875f*h,h*.024f,0xffbea36d);}
  @Override protected void onDraw(Canvas c){float w=getWidth(),h=getHeight();p.reset();p.setAntiAlias(true);p.setAlpha(255);p.setColor(Color.WHITE);p.setStyle(Paint.Style.FILL);c.drawColor(Color.BLACK);c.drawBitmap(bg,null,new RectF(0,0,w,h),p);float mr=h*.034f,pr=h*.014f;
   if(screen==MENU){drawMenu(c,w,h);return;}if(screen==LOBBY){drawLobby(c,w,h);return;}if(screen==SECRET){drawSecret(c,w,h);return;}
   peg(c,.405f*w,.047f*h,h*.014f,true);text(c,"ヒット",.448f*w,.058f*h,h*.030f,0xffffecd0);peg(c,.535f*w,.047f*h,h*.014f,false);text(c,"ブロー",.585f*w,.058f*h,h*.030f,0xffffecd0);
   int active=Math.min(7,tries.size());p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(h*.005f);p.setShadowLayer(h*.014f,0,0,0xffffb52f);p.setColor(0xffffcf62);c.drawCircle(HX[active]*w/1280f,.181f*h,h*.045f,p);p.clearShadowLayer();
   for(int col=0;col<8;col++){int[]v=col<tries.size()?tries.get(col):(col==tries.size()&&!ended?now:null);if(v!=null)for(int s=0;s<4;s++)if(v[s]>=0&&!(col==tries.size()&&s==movingSlot&&putT<1))marble(c,GX[col][s]*w/1280f,GY[col][s]*h/720f,mr,v[s]);if(col<marks.size()){int hit=marks.get(col)[0],blow=marks.get(col)[1],n=0,show=col==markCol?(int)(pinT*4.01f):4;for(int k=0;k<hit;k++,n++)if(n<show)peg(c,MX[col][n]*w/1280f,MY[col][n]*h/720f,pr,true);for(int k=0;k<blow;k++,n++)if(n<show)peg(c,MX[col][n]*w/1280f,MY[col][n]*h/720f,pr,false);}}
   float ax=1170*w/1280f;for(int i=0;i<4;i++)marble(c,ax,GY[7][i]*h/720f,mr,answer[i]);RectF lid=new RectF(1134*w/1280f,249*h/720f,1211*w/1280f,539*h/720f);float door=Math.max(.045f,(float)Math.cos(lidT*Math.PI*.5));c.save();c.scale(door,1,lid.right,lid.centerY());answerLid(c,lid,h);c.restore();p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(h*.005f);p.setColor(0xffb99a61);c.drawLine(lid.right,lid.top+h*.012f,lid.right,lid.bottom-h*.012f,p);
   palette.clear();for(int i=0;i<6;i++){float x=PX[i]*w/1280f,y=617*h/720f;palette.add(new RectF(x-mr*1.3f,y-mr*1.3f,x+mr*1.3f,y+mr*1.3f));marble(c,x,y,mr,i);if(i==selectedColor){p.setShader(null);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(h*.005f);p.setColor(0xffffcf62);p.setShadowLayer(h*.012f,0,0,0xffffb52f);c.drawCircle(x,y,mr*1.28f,p);p.clearShadowLayer();}}
   if(!ended&&(selectedColor>=0||dragging)&&(!online||myTurn)){int col=Math.min(7,tries.size());for(int s=0;s<4;s++){float x=GX[col][s]*w/1280f,y=GY[col][s]*h/720f;p.setShader(null);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(h*.004f);p.setColor(now[s]<0?0xffffcf62:0xffac8c50);p.setShadowLayer(h*.008f,0,0,0xffffb52f);c.drawCircle(x,y,mr*1.18f,p);p.clearShadowLayer();}}
   undo.set(.785f*w,.835f*h,.855f*w,.925f*h);ok.set(.865f*w,.825f*h,.958f*w,.925f*h);rr(c,undo,h*.018f,0xff292b2c);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(2);p.setColor(0xffb89a68);c.drawRoundRect(undo,h*.018f,h*.018f,p);text(c,"↶",undo.centerX(),undo.centerY()+h*.012f,h*.038f,0xffe8ddc9);rr(c,ok,h*.019f,filled()==4||ended?0xff9a6c2e:0xff45413b);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(2);p.setColor(0xffd1b47c);c.drawRoundRect(ok,h*.019f,h*.019f,p);text(c,ended?"NEW":"OK",ok.centerX(),ok.centerY()+h*.012f,h*.034f,0xfffff1d1);
   gear.set(.843f*w,.015f*h,.91f*w,.095f*h);restart.set(.925f*w,.015f*h,.985f*w,.095f*h);
   if(putT<1&&movingColor>=0){int col=Math.min(7,tries.size());float sx=PX[movingColor]*w/1280f,sy=617*h/720f,ex=GX[col][movingSlot]*w/1280f,ey=GY[col][movingSlot]*h/720f,t=putT;marble(c,sx+(ex-sx)*t,sy+(ey-sy)*t-(float)Math.sin(Math.PI*t)*h*.10f,mr,movingColor);}
   if(dragging&&dragColor>=0)marble(c,dragX,dragY,mr*1.08f,dragColor);
   if(resultT<1){float alpha=resultT<.12f?resultT/.12f:(resultT>.78f?(1-resultT)/.22f:1);alpha=Math.max(0,Math.min(1,alpha));RectF banner=new RectF(.39f*w,.435f*h,.61f*w,.555f*h);rr(c,banner,h*.028f,Color.argb((int)(220*alpha),25,25,24));p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(2);p.setColor(Color.argb((int)(210*alpha),190,151,84));c.drawRoundRect(banner,h*.028f,h*.028f,p);text(c,lastHit+" ヒット   "+lastBlow+" ブロー",.5f*w,.512f*h,h*.040f,Color.argb((int)(255*alpha),255,240,210));p.setAlpha(255);}
   if(win&&partyT>0&&partyT<.98f)for(int i=0;i<16;i++){float x=(i*97)%w,y=((i*.191f+partyT*1.3f)%1)*h;p.setColor(C[i%6]);p.setStyle(Paint.Style.FILL);c.save();c.rotate(i*31+partyT*360,x,y);c.drawRect(x-3,y-7,x+3,y+7,p);c.restore();}
   if(online&&!ended){text(c,"ROOM "+roomCode+"   "+(myTurn?"YOUR TURN":"OPPONENT"),.73f*w,.058f*h,h*.020f,myTurn?0xffffd77a:0xffc8b795);}if(settings)drawSettings(c,w,h);
  }
  void drawSettings(Canvas c,float w,float h){p.setColor(0x99000000);p.setStyle(Paint.Style.FILL);c.drawRect(0,0,w,h,p);RectF box=new RectF(.31f*w,.25f*h,.69f*w,.73f*h);rr(c,box,h*.03f,0xff242526);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(3);p.setColor(0xffad8a52);c.drawRoundRect(box,h*.03f,h*.03f,p);text(c,"設定",.5f*w,.34f*h,h*.045f,0xffffefd0);option.set(.37f*w,.41f*h,.63f*w,.53f*h);rr(c,option,h*.025f,duplicates?0xff87552e:0xff3b3c3c);text(c,"答えの同色　"+(duplicates?"あり":"なし"),option.centerX(),option.centerY()+h*.012f,h*.032f,Color.WHITE);close.set(.41f*w,.59f*h,.59f*w,.67f*h);rr(c,close,h*.022f,0xff8b6b3b);text(c,"閉じる",close.centerX(),close.centerY()+h*.011f,h*.03f,Color.WHITE);}
  void anim(ValueAnimator a){a.addUpdateListener(v->invalidate());a.start();}
  String csv(int[]v){return v[0]+","+v[1]+","+v[2]+","+v[3];}
  int[] unCsv(String s){int[]v={-1,-1,-1,-1};try{String[]q=s.split(",");for(int i=0;i<4&&i<q.length;i++)v[i]=Integer.parseInt(q[i]);}catch(Exception ignored){}return v;}
  String request(String method,String path,String body)throws Exception{URL u=new URL(DB+path+".json?auth="+URLEncoder.encode(token,"UTF-8"));HttpURLConnection c=(HttpURLConnection)u.openConnection();c.setRequestMethod(method);c.setConnectTimeout(8000);c.setReadTimeout(8000);c.setRequestProperty("Content-Type","application/json; charset=UTF-8");if(body!=null){c.setDoOutput(true);try(OutputStream o=c.getOutputStream()){o.write(body.getBytes(StandardCharsets.UTF_8));}}int code=c.getResponseCode();InputStream in=code<400?c.getInputStream():c.getErrorStream();StringBuilder s=new StringBuilder();if(in!=null)try(BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8))){String line;while((line=r.readLine())!=null)s.append(line);}if(code>=400)throw new IOException(code+" "+s);return s.toString();}
  void authenticate(Runnable next){if(!token.isEmpty()){next.run();return;}busy=true;onlineMsg="接続しています…";invalidate();net.execute(()->{try{URL u=new URL("https://identitytoolkit.googleapis.com/v1/accounts:signUp?key="+API_KEY);HttpURLConnection c=(HttpURLConnection)u.openConnection();c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");try(OutputStream o=c.getOutputStream()){o.write("{\"returnSecureToken\":true}".getBytes(StandardCharsets.UTF_8));}JSONObject j=new JSONObject(read(c));token=j.getString("idToken");uid=j.getString("localId");ui.post(()->{busy=false;next.run();});}catch(Exception e){ui.post(()->fail("接続できません。通信を確認してください"));}});}
  String read(HttpURLConnection c)throws Exception{InputStream in=c.getResponseCode()<400?c.getInputStream():c.getErrorStream();StringBuilder s=new StringBuilder();try(BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8))){String q;while((q=r.readLine())!=null)s.append(q);}if(c.getResponseCode()>=400)throw new IOException(s.toString());return s.toString();}
  void fail(String s){busy=false;onlineMsg=s;tone.startTone(ToneGenerator.TONE_PROP_NACK,100);invalidate();}
  void createRoom(){authenticate(()->{busy=true;onlineMsg="部屋を用意しています…";invalidate();net.execute(()->{try{String code;do{code=String.format(Locale.US,"%04d",new Random().nextInt(10000));}while(!"null".equals(request("GET","/rooms/"+code,null)));JSONObject j=new JSONObject();j.put("hostId",uid).put("hostReady",false).put("status","waiting").put("turn","host").put("moveIndex",0);request("PUT","/rooms/"+code,j.toString());String finalCode=code;ui.post(()->{roomCode=finalCode;host=true;role="host";online=true;busy=false;ready=false;remoteMoveCount=0;Arrays.fill(now,-1);selectedColor=-1;screen=SECRET;startPolling();invalidate();});}catch(Exception e){ui.post(()->fail("部屋を作れませんでした"));}});});}
  void joinRoom(){if(roomCode.length()!=4)return;authenticate(()->{busy=true;onlineMsg="部屋を探しています…";invalidate();net.execute(()->{try{String raw=request("GET","/rooms/"+roomCode,null);if("null".equals(raw))throw new IOException();JSONObject room=new JSONObject(raw);if(room.has("guestId")&&!room.optString("guestId").isEmpty()){ui.post(()->fail("その部屋は対戦中です"));return;}JSONObject j=new JSONObject();j.put("guestId",uid).put("guestReady",false).put("status","setting");request("PATCH","/rooms/"+roomCode,j.toString());ui.post(()->{host=false;role="guest";online=true;busy=false;ready=false;remoteMoveCount=0;Arrays.fill(now,-1);selectedColor=-1;screen=SECRET;startPolling();invalidate();});}catch(Exception e){ui.post(()->fail("部屋が見つかりません"));}});});}
  void submitSecret(){if(filled()<4||ready||busy)return;busy=true;JSONObject j=new JSONObject();try{j.put(role+"Secret",csv(now)).put(role+"Ready",true);}catch(Exception ignored){}net.execute(()->{try{request("PATCH","/rooms/"+roomCode,j.toString());ui.post(()->{ready=true;busy=false;onlineMsg="相手を待っています…";invalidate();});}catch(Exception e){ui.post(()->fail("送信できませんでした"));}});}
  void startPolling(){if(polling)return;polling=true;pollOnce();}
  void pollOnce(){if(!polling||!online)return;net.execute(()->{try{String raw=request("GET","/rooms/"+roomCode,null);if("null".equals(raw))throw new IOException();JSONObject room=new JSONObject(raw);ui.post(()->applyRoom(room));}catch(Exception ignored){}finally{ui.postDelayed(()->pollOnce(),1200);}});}
  void applyRoom(JSONObject room){try{boolean hr=room.optBoolean("hostReady"),gr=room.optBoolean("guestReady");if(hr&&gr&&!"playing".equals(room.optString("status"))&&host){JSONObject j=new JSONObject();j.put("status","playing").put("turn","host");net.execute(()->{try{request("PATCH","/rooms/"+roomCode,j.toString());}catch(Exception ignored){}});}if(hr&&gr){opponentSecret=room.optString(host?"guestSecret":"hostSecret");if(screen==SECRET){screen=PLAY;newGame();online=true;ended=false;}}
    myTurn=role.equals(room.optString("turn"));JSONArray mine=new JSONArray();JSONObject moves=room.optJSONObject("moves");if(moves!=null){ArrayList<Integer>ids=new ArrayList<>();Iterator<String>it=moves.keys();while(it.hasNext())try{ids.add(Integer.parseInt(it.next()));}catch(Exception ignored){}Collections.sort(ids);for(int id:ids){JSONObject m=moves.optJSONObject(String.valueOf(id));if(m!=null&&role.equals(m.optString("player")))mine.put(m);}}
    if(mine.length()!=remoteMoveCount){tries.clear();marks.clear();for(int i=0;i<mine.length();i++){JSONObject m=mine.getJSONObject(i);tries.add(unCsv(m.getString("guess")));marks.add(new int[]{m.getInt("hit"),m.getInt("blow")});lastHit=m.getInt("hit");lastBlow=m.getInt("blow");}remoteMoveCount=mine.length();Arrays.fill(now,-1);editHistory.clear();}
    String winner=room.optString("winner");if(!winner.isEmpty()){ended=true;win=role.equals(winner);int[]a=unCsv(opponentSecret);System.arraycopy(a,0,answer,0,4);lidT=1;}
  }catch(Exception ignored){}invalidate();}
  void judgeOnline(){if(filled()<4||!myTurn||busy||opponentSecret.isEmpty())return;int[]a=unCsv(opponentSecret);boolean[]ua=new boolean[4],ug=new boolean[4];int hit=0,blow=0;for(int i=0;i<4;i++)if(now[i]==a[i]){hit++;ua[i]=ug[i]=true;}for(int i=0;i<4;i++)if(!ug[i])for(int j=0;j<4;j++)if(!ua[j]&&now[i]==a[j]){blow++;ua[j]=true;break;}lastHit=hit;lastBlow=blow;String guess=csv(now);int index=remoteMoveCount*2+(host?0:1);busy=true;myTurn=false;JSONObject j=new JSONObject();try{j.put("moves/"+index+"/player",role).put("moves/"+index+"/guess",guess).put("moves/"+index+"/hit",hit).put("moves/"+index+"/blow",blow).put("turn",host?"guest":"host");if(hit==4)j.put("winner",role).put("status","ended");else if(remoteMoveCount>=7&&!host)j.put("winner","draw").put("status","ended");}catch(Exception ignored){}net.execute(()->{try{request("PATCH","/rooms/"+roomCode,j.toString());ui.post(()->{busy=false;resultT=0;ValueAnimator v=ValueAnimator.ofFloat(0,1);v.setDuration(1700);v.addUpdateListener(x->resultT=(float)x.getAnimatedValue());anim(v);});}catch(Exception e){ui.post(()->{busy=false;myTurn=true;fail("送信できませんでした");});}});}
  void leaveOnline(){polling=false;online=false;host=false;ready=false;myTurn=false;busy=false;remoteMoveCount=0;roomCode="";onlineMsg="";screen=MENU;newGame();invalidate();}
  int activeSlotAt(float x,float y){if(ended||tries.size()>=8||(online&&!myTurn))return-1;int col=tries.size();float r=getHeight()*.060f;for(int s=0;s<4;s++){float dx=x-GX[col][s]*getWidth()/1280f,dy=y-GY[col][s]*getHeight()/720f;if(dx*dx+dy*dy<=r*r)return s;}return-1;}
  void placeAt(int slot,int color,boolean animate){if(ended||settings||slot<0||slot>3||color<0)return;editHistory.add(now.clone());now[slot]=color;movingColor=color;movingSlot=slot;putT=animate?0:1;if(animate){ValueAnimator a=ValueAnimator.ofFloat(0,1);a.setDuration(300);a.setInterpolator(new OvershootInterpolator(.45f));a.addUpdateListener(v->putT=(float)v.getAnimatedValue());anim(a);}tone.startTone(ToneGenerator.TONE_PROP_BEEP,35);performHapticFeedback(HapticFeedbackConstants.KEYBOARD_TAP);selectedColor=-1;invalidate();}
  void judge(){if(online){judgeOnline();return;}if(ended){newGame();return;}if(filled()<4)return;boolean[]ua=new boolean[4],ug=new boolean[4];int hit=0,blow=0;for(int i=0;i<4;i++)if(now[i]==answer[i]){hit++;ua[i]=ug[i]=true;}for(int i=0;i<4;i++)if(!ug[i])for(int j=0;j<4;j++)if(!ua[j]&&now[i]==answer[j]){blow++;ua[j]=true;break;}lastHit=hit;lastBlow=blow;resultT=0;ValueAnimator result=ValueAnimator.ofFloat(0,1);result.setDuration(1700);result.addUpdateListener(v->resultT=(float)v.getAnimatedValue());anim(result);tries.add(now.clone());marks.add(new int[]{hit,blow});Arrays.fill(now,-1);editHistory.clear();selectedColor=-1;markCol=tries.size()-1;pinT=0;tone.startTone(ToneGenerator.TONE_PROP_ACK,90);ValueAnimator a=ValueAnimator.ofFloat(0,1);a.setDuration(620);a.setInterpolator(new OvershootInterpolator(.3f));a.addUpdateListener(v->pinT=(float)v.getAnimatedValue());anim(a);if(hit==4||tries.size()==8){ended=true;win=hit==4;ValueAnimator l=ValueAnimator.ofFloat(0,1);l.setStartDelay(420);l.setDuration(700);l.setInterpolator(new DecelerateInterpolator());l.addUpdateListener(v->lidT=(float)v.getAnimatedValue());anim(l);if(win){ValueAnimator f=ValueAnimator.ofFloat(0,1);f.setStartDelay(500);f.setDuration(1400);f.addUpdateListener(v->partyT=(float)v.getAnimatedValue());anim(f);}}}
  @Override public boolean onTouchEvent(MotionEvent e){float x=e.getX(),y=e.getY();if(screen==MENU){if(e.getAction()==MotionEvent.ACTION_UP){if(soloBtn.contains(x,y)){online=false;screen=PLAY;newGame();}else if(onlineBtn.contains(x,y)){screen=LOBBY;roomCode="";onlineMsg="4桁のルームコード";}invalidate();}return true;}if(screen==LOBBY){if(e.getAction()==MotionEvent.ACTION_UP&&!busy){for(int i=0;i<keys.size();i++)if(keys.get(i).contains(x,y)&&roomCode.length()<4){roomCode+=String.valueOf(i<9?i+1:0);tone.startTone(ToneGenerator.TONE_PROP_BEEP,30);invalidate();return true;}if(backBtn.contains(x,y)){screen=MENU;roomCode="";}else if(createBtn.contains(x,y)){roomCode="";createRoom();}else if(joinBtn.contains(x,y)&&roomCode.length()==4)joinRoom();else if(y>.24f*getHeight()&&y<.39f*getHeight()&&roomCode.length()>0)roomCode=roomCode.substring(0,roomCode.length()-1);invalidate();}return true;}if(screen==SECRET){if(e.getAction()==MotionEvent.ACTION_UP&&!busy){if(backBtn.contains(x,y)){leaveOnline();return true;}if(secretOk.contains(x,y)){submitSecret();return true;}for(int i=0;i<palette.size();i++)if(palette.get(i).contains(x,y)){selectedColor=i;invalidate();return true;}float r=getHeight()*.065f;for(int s=0;s<4;s++){float sx=(.365f+s*.09f)*getWidth(),sy=.425f*getHeight();if((x-sx)*(x-sx)+(y-sy)*(y-sy)<r*r&&selectedColor>=0){editHistory.add(now.clone());now[s]=selectedColor;selectedColor=-1;invalidate();return true;}}}return true;}
   if(e.getAction()==MotionEvent.ACTION_DOWN){downX=dragX=x;downY=dragY=y;dragMoved=false;if(!settings&&!ended&&(!online||myTurn))for(int i=0;i<palette.size();i++)if(palette.get(i).contains(x,y)){dragging=true;dragColor=selectedColor=i;invalidate();return true;}return true;}if(e.getAction()==MotionEvent.ACTION_MOVE){if(dragging){dragX=x;dragY=y;if(Math.abs(x-downX)+Math.abs(y-downY)>getHeight()*.025f)dragMoved=true;invalidate();}return true;}if(e.getAction()!=MotionEvent.ACTION_UP)return true;if(settings){if(option.contains(x,y)&&!online){duplicates=!duplicates;newGame();settings=true;}else if(close.contains(x,y))settings=false;invalidate();return true;}if(dragging){int slot=activeSlotAt(x,y);boolean moved=dragMoved;int color=dragColor;dragging=false;dragColor=-1;if(slot>=0)placeAt(slot,color,!moved);else invalidate();return true;}int slot=activeSlotAt(x,y);if(slot>=0&&selectedColor>=0){placeAt(slot,selectedColor,true);return true;}if(ok.contains(x,y)){if(online&&ended)leaveOnline();else judge();}else if(undo.contains(x,y)){if(!editHistory.isEmpty()){int[]prev=editHistory.remove(editHistory.size()-1);System.arraycopy(prev,0,now,0,4);}selectedColor=-1;}else if(gear.contains(x,y))settings=true;else if(restart.contains(x,y)){if(online)leaveOnline();else newGame();}invalidate();return true;}
  @Override protected void onDetachedFromWindow(){polling=false;net.shutdownNow();tone.release();super.onDetachedFromWindow();}
 }
}
