package dev.ryu4696.hitandblow;

import android.animation.ValueAnimator;
import android.app.Activity;
import android.graphics.*;
import android.media.*;
import android.os.Bundle;
import android.view.*;
import android.view.animation.*;
import java.util.*;

public class MainActivity extends Activity {
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setNavigationBarColor(Color.BLACK);setContentView(new Game());}
 class Game extends View {
  final int[] C={0xff2459df,0xffed3838,0xff25bd43,0xffffd21d,0xffe85ccf,0xffe9eeeb};
  final float[] CX={.1190f,.2178f,.3184f,.4186f,.5183f,.6178f,.7175f,.8174f};
  final float[] SY={.4078f,.5064f,.6038f,.7010f};
  final float[] PX={.3118f,.3906f,.4688f,.5464f,.6243f,.7026f};
  final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);final Path path=new Path();final Bitmap bg;
  final ArrayList<int[]> tries=new ArrayList<>(),marks=new ArrayList<>();final int[] now={-1,-1,-1,-1};final int[] answer=new int[4];
  final ArrayList<RectF> palette=new ArrayList<>();final RectF ok=new RectF(),undo=new RectF(),gear=new RectF(),restart=new RectF(),option=new RectF(),close=new RectF();
  final ToneGenerator tone=new ToneGenerator(AudioManager.STREAM_MUSIC,34);
  boolean duplicates=false,ended=false,win=false,settings=false;int movingColor=-1,movingSlot=-1,markCol=-1,lastHit=0,lastBlow=0;float putT=1,pinT=1,lidT=0,partyT=0,resultT=1;
  Game(){super(MainActivity.this);setLayerType(LAYER_TYPE_SOFTWARE,null);bg=BitmapFactory.decodeResource(getResources(),R.drawable.game_board_v6);newGame();}
  void newGame(){tries.clear();marks.clear();Arrays.fill(now,-1);ended=win=false;putT=pinT=1;lidT=partyT=0;ArrayList<Integer>b=new ArrayList<>();for(int i=0;i<6;i++)b.add(i);Collections.shuffle(b);Random r=new Random();for(int i=0;i<4;i++)answer[i]=duplicates?r.nextInt(6):b.get(i);invalidate();}
  int filled(){int n=0;for(int v:now)if(v>=0)n++;return n;}
  int mix(int a,int b,float t){return Color.rgb((int)(Color.red(a)*(1-t)+Color.red(b)*t),(int)(Color.green(a)*(1-t)+Color.green(b)*t),(int)(Color.blue(a)*(1-t)+Color.blue(b)*t));}
  void rr(Canvas c,RectF r,float rad,int color){p.setShader(null);p.setStyle(Paint.Style.FILL);p.setColor(color);p.clearShadowLayer();c.drawRoundRect(r,rad,rad,p);}
  void text(Canvas c,String s,float x,float y,float z,int color){p.setShader(null);p.setStyle(Paint.Style.FILL);p.setTypeface(Typeface.create("sans",Typeface.BOLD));p.setTextAlign(Paint.Align.CENTER);p.setTextSize(z);p.setColor(color);c.drawText(s,x,y,p);}
  void marble(Canvas c,float x,float y,float r,int idx){int base=C[idx];p.setShader(new RadialGradient(x-r*.35f,y-r*.42f,r*1.35f,new int[]{mix(base,Color.WHITE,.54f),base,mix(base,Color.BLACK,.50f)},new float[]{0,.45f,1},Shader.TileMode.CLAMP));p.setStyle(Paint.Style.FILL);p.setShadowLayer(r*.28f,0,r*.23f,0xbb000000);c.drawCircle(x,y,r,p);p.clearShadowLayer();p.setShader(null);c.save();path.reset();path.addCircle(x,y,r*.87f,Path.Direction.CW);c.clipPath(path);p.setColor(0xb8ffffff);p.setStrokeCap(Paint.Cap.ROUND);p.setStrokeWidth(r*.22f);p.setStyle(Paint.Style.STROKE);
   if(idx==0){c.drawLine(x-r,y,x+r,y,p);c.drawLine(x,y-r,x,y+r,p);}else if(idx==1){p.setStyle(Paint.Style.FILL);float q=r*.61f;for(int a=-2;a<2;a++)for(int b=-2;b<2;b++)if((a+b)%2==0)c.drawRect(x+a*q,y+b*q,x+(a+1)*q,y+(b+1)*q,p);}else if(idx==2){for(int k=-1;k<=1;k++){path.reset();path.moveTo(x-r*1.2f,y+k*r*.72f);path.cubicTo(x-r*.5f,y+(k-.8f)*r*.72f,x+r*.2f,y+(k+.8f)*r*.72f,x+r*1.2f,y+k*r*.72f);c.drawPath(path,p);}}else if(idx==3){p.setStyle(Paint.Style.FILL);for(int a=-2;a<2;a++)for(int b=-2;b<2;b++){path.reset();path.moveTo(x+a*r*.75f,y+b*r*.75f-r*.28f);path.lineTo(x+a*r*.75f+r*.28f,y+b*r*.75f);path.lineTo(x+a*r*.75f,y+b*r*.75f+r*.28f);path.lineTo(x+a*r*.75f-r*.28f,y+b*r*.75f);path.close();c.drawPath(path,p);}}else if(idx==4){for(int k=-2;k<=2;k++)c.drawLine(x-r*1.5f+k*r*.62f,y+r,x+r*.5f+k*r*.62f,y-r,p);}else for(int k=-2;k<=2;k++)c.drawLine(x-r,y+k*r*.5f,x+r,y+k*r*.5f,p);c.restore();p.setStyle(Paint.Style.FILL);p.setColor(0xccffffff);c.drawOval(new RectF(x-r*.48f,y-r*.56f,x-r*.12f,y-r*.23f),p);}
  void peg(Canvas c,float x,float y,float r,boolean hit){int b=hit?0xffd86620:0xffeee9dd;p.setShader(new RadialGradient(x-r*.35f,y-r*.4f,r*1.3f,new int[]{Color.WHITE,b,mix(b,Color.BLACK,.45f)},new float[]{0,.42f,1},Shader.TileMode.CLAMP));p.setStyle(Paint.Style.FILL);p.setShadowLayer(r*.3f,0,r*.2f,0xcc000000);c.drawCircle(x,y,r,p);p.clearShadowLayer();p.setShader(null);}
  @Override protected void onDraw(Canvas c){float w=getWidth(),h=getHeight();p.reset();p.setAntiAlias(true);p.setAlpha(255);p.setColor(Color.WHITE);p.setStyle(Paint.Style.FILL);c.drawColor(Color.BLACK);c.drawBitmap(bg,null,new RectF(0,0,w,h),p);float mr=h*.034f,pr=h*.014f;
   peg(c,.405f*w,.047f*h,h*.014f,true);text(c,"ヒット",.448f*w,.058f*h,h*.030f,0xffffecd0);peg(c,.535f*w,.047f*h,h*.014f,false);text(c,"ブロー",.585f*w,.058f*h,h*.030f,0xffffecd0);
   int active=Math.min(7,tries.size());p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(h*.005f);p.setShadowLayer(h*.012f,0,0,0xffff35cf);p.setColor(0xffff63d6);c.drawCircle(CX[active]*w,.181f*h,h*.045f,p);p.clearShadowLayer();
   for(int col=0;col<8;col++){int[]v=col<tries.size()?tries.get(col):(col==tries.size()&&!ended?now:null);if(v!=null)for(int s=0;s<4;s++)if(v[s]>=0&&!(col==tries.size()&&s==movingSlot&&putT<1))marble(c,CX[col]*w,SY[s]*h,mr,v[s]);if(col<marks.size()){int hit=marks.get(col)[0],blow=marks.get(col)[1],n=0,show=col==markCol?(int)(pinT*4.01f):4;for(int k=0;k<hit;k++,n++)if(n<show)peg(c,(CX[col]+(n%2==0?-.012f:.012f))*w,(.262f+(n/2)*.047f)*h,pr,true);for(int k=0;k<blow;k++,n++)if(n<show)peg(c,(CX[col]+(n%2==0?-.012f:.012f))*w,(.262f+(n/2)*.047f)*h,pr,false);}}
   float ax=.918f*w;for(int i=0;i<4;i++)marble(c,ax,SY[i]*h,mr,answer[i]);float yoff=lidT*h*.57f;RectF lid=new RectF(.888f*w,.325f*h-yoff,.949f*w,.725f*h-yoff);rr(c,lid,h*.018f,0xff25282a);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(h*.004f);p.setColor(0xffa98a55);c.drawRoundRect(lid,h*.018f,h*.018f,p);if(lidT<.85f){text(c,"◆",lid.centerX(),lid.centerY()+h*.015f,h*.055f,0xff9f895e);}
   palette.clear();for(int i=0;i<6;i++){float x=PX[i]*w,y=.855f*h;palette.add(new RectF(x-mr*1.3f,y-mr*1.3f,x+mr*1.3f,y+mr*1.3f));marble(c,x,y,mr,i);}
   undo.set(.785f*w,.835f*h,.855f*w,.925f*h);ok.set(.865f*w,.825f*h,.958f*w,.925f*h);rr(c,undo,h*.018f,0xff292b2c);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(2);p.setColor(0xffb89a68);c.drawRoundRect(undo,h*.018f,h*.018f,p);text(c,"↶",undo.centerX(),undo.centerY()+h*.012f,h*.038f,0xffe8ddc9);rr(c,ok,h*.019f,filled()==4||ended?0xff9a6c2e:0xff45413b);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(2);p.setColor(0xffd1b47c);c.drawRoundRect(ok,h*.019f,h*.019f,p);text(c,ended?"NEW":"OK",ok.centerX(),ok.centerY()+h*.012f,h*.034f,0xfffff1d1);
   gear.set(.843f*w,.015f*h,.91f*w,.095f*h);restart.set(.925f*w,.015f*h,.985f*w,.095f*h);
   if(putT<1&&movingColor>=0){float sx=PX[movingColor]*w,sy=.855f*h,ex=CX[Math.min(7,tries.size())]*w,ey=SY[movingSlot]*h,t=putT;marble(c,sx+(ex-sx)*t,sy+(ey-sy)*t-(float)Math.sin(Math.PI*t)*h*.10f,mr,movingColor);}
   if(resultT<1){float alpha=resultT<.12f?resultT/.12f:(resultT>.78f?(1-resultT)/.22f:1);alpha=Math.max(0,Math.min(1,alpha));RectF banner=new RectF(.39f*w,.435f*h,.61f*w,.555f*h);rr(c,banner,h*.028f,Color.argb((int)(220*alpha),25,25,24));p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(2);p.setColor(Color.argb((int)(210*alpha),190,151,84));c.drawRoundRect(banner,h*.028f,h*.028f,p);text(c,lastHit+" ヒット   "+lastBlow+" ブロー",.5f*w,.512f*h,h*.040f,Color.argb((int)(255*alpha),255,240,210));p.setAlpha(255);}
   if(win&&partyT>0&&partyT<.98f)for(int i=0;i<16;i++){float x=(i*97)%w,y=((i*.191f+partyT*1.3f)%1)*h;p.setColor(C[i%6]);p.setStyle(Paint.Style.FILL);c.save();c.rotate(i*31+partyT*360,x,y);c.drawRect(x-3,y-7,x+3,y+7,p);c.restore();}
   if(settings)drawSettings(c,w,h);
  }
  void drawSettings(Canvas c,float w,float h){p.setColor(0x99000000);p.setStyle(Paint.Style.FILL);c.drawRect(0,0,w,h,p);RectF box=new RectF(.31f*w,.25f*h,.69f*w,.73f*h);rr(c,box,h*.03f,0xff242526);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(3);p.setColor(0xffad8a52);c.drawRoundRect(box,h*.03f,h*.03f,p);text(c,"設定",.5f*w,.34f*h,h*.045f,0xffffefd0);option.set(.37f*w,.41f*h,.63f*w,.53f*h);rr(c,option,h*.025f,duplicates?0xff87552e:0xff3b3c3c);text(c,"答えの同色　"+(duplicates?"あり":"なし"),option.centerX(),option.centerY()+h*.012f,h*.032f,Color.WHITE);close.set(.41f*w,.59f*h,.59f*w,.67f*h);rr(c,close,h*.022f,0xff8b6b3b);text(c,"閉じる",close.centerX(),close.centerY()+h*.011f,h*.03f,Color.WHITE);}
  void anim(ValueAnimator a){a.addUpdateListener(v->invalidate());a.start();}
  void choose(int color){if(ended||settings||filled()==4)return;int s=filled();now[s]=color;movingColor=color;movingSlot=s;putT=0;tone.startTone(ToneGenerator.TONE_PROP_BEEP,35);ValueAnimator a=ValueAnimator.ofFloat(0,1);a.setDuration(320);a.setInterpolator(new OvershootInterpolator(.5f));a.addUpdateListener(v->putT=(float)v.getAnimatedValue());anim(a);performHapticFeedback(HapticFeedbackConstants.KEYBOARD_TAP);}
  void judge(){if(ended){newGame();return;}if(filled()<4)return;boolean[]ua=new boolean[4],ug=new boolean[4];int hit=0,blow=0;for(int i=0;i<4;i++)if(now[i]==answer[i]){hit++;ua[i]=ug[i]=true;}for(int i=0;i<4;i++)if(!ug[i])for(int j=0;j<4;j++)if(!ua[j]&&now[i]==answer[j]){blow++;ua[j]=true;break;}lastHit=hit;lastBlow=blow;resultT=0;ValueAnimator result=ValueAnimator.ofFloat(0,1);result.setDuration(1700);result.addUpdateListener(v->resultT=(float)v.getAnimatedValue());anim(result);tries.add(now.clone());marks.add(new int[]{hit,blow});Arrays.fill(now,-1);markCol=tries.size()-1;pinT=0;tone.startTone(ToneGenerator.TONE_PROP_ACK,90);ValueAnimator a=ValueAnimator.ofFloat(0,1);a.setDuration(620);a.setInterpolator(new OvershootInterpolator(.3f));a.addUpdateListener(v->pinT=(float)v.getAnimatedValue());anim(a);if(hit==4||tries.size()==8){ended=true;win=hit==4;ValueAnimator l=ValueAnimator.ofFloat(0,1);l.setStartDelay(420);l.setDuration(700);l.setInterpolator(new DecelerateInterpolator());l.addUpdateListener(v->lidT=(float)v.getAnimatedValue());anim(l);if(win){ValueAnimator f=ValueAnimator.ofFloat(0,1);f.setStartDelay(500);f.setDuration(1400);f.addUpdateListener(v->partyT=(float)v.getAnimatedValue());anim(f);}}}
  @Override public boolean onTouchEvent(MotionEvent e){if(e.getAction()!=MotionEvent.ACTION_UP)return true;float x=e.getX(),y=e.getY();if(settings){if(option.contains(x,y)){duplicates=!duplicates;newGame();settings=true;}else if(close.contains(x,y))settings=false;invalidate();return true;}for(int i=0;i<palette.size();i++)if(palette.get(i).contains(x,y)){choose(i);return true;}if(ok.contains(x,y))judge();else if(undo.contains(x,y)){int n=filled();if(n>0)now[n-1]=-1;}else if(gear.contains(x,y))settings=true;else if(restart.contains(x,y))newGame();invalidate();return true;}
  @Override protected void onDetachedFromWindow(){tone.release();super.onDetachedFromWindow();}
 }
}
